services:
  db:
    image: postgres:16-alpine
    container_name: companion_db
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: companion
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U app -d companion']
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - db:/var/lib/postgresql/data

  backend:
    build: .
    container_name: companion_api
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://app:app@db:5432/companion?schema=public
      JWT_SECRET: dev_secret
      JWT_EXPIRES_IN: 7d
      PORT: 3000
      ADMIN_EMAIL: admin@local
      ADMIN_PASSWORD: admin123
    ports:
      - '3000:3000'
    command: sh -c "npx prisma migrate deploy && node dist/main.js"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '8081:80'
    depends_on:
      db:
        condition: service_healthy

volumes:
  db:
